package de.timseidel.doppelkopf.util

import java.util.UUID

/**
A utility class for generating unique IDs and codes.
 */
class IdGenerator {

    companion object {
        /**
         * Generates a unique ID string by concatenating a provided object tag with a UUID.
         *
         * @param objectTag The tag to be included in the generated ID. Defaults to "id" if not provided.
         * @return A unique ID string generated by concatenating the object tag with a UUID.
         */
        fun generateIdWithTimestamp(objectTag: String = "id"): String {
            return "${objectTag}_${System.currentTimeMillis()}_${UUID.randomUUID().toString().substring(0, 8)}"
        }

        /**
         * Generates a unique six-digit group code using random digits.
         *
         * @return A unique six-digit group code.
         */
        fun generateGroupCode(): String {
            val random = java.security.SecureRandom()
            val code = random.nextInt(1000000)
            return code.toString().padStart(6, '0')
        }
    }
}
